### ISSUE TITLE
Issues generating slugs from Chinese or Japanese

### ISSUE THREAD

**Issue by neo22s** [keyvanakbary/slugifier#14]
When I do the slug of ホームホーム (JP) returns empty.

Same with 回家回家 in chinese.

Maybe detecting the usage of https://en.wikipedia.org/wiki/CJK_characters and in that case do nothing since we can not transliterate/use modifiers?

**Comment by neo22s** [comment]
I have tried this:

```
$cjk_encoding = array('Big5','EUC-JP','EUC-KR','GB18030','GB2312','ISO 2022-JP','KS C 5861','Shift-JIS');
            $encoding_detected = mb_detect_encoding($title,implode(',',$cjk_encoding));

        if (in_array($encoding_detected,$cjk_encoding))
            echo 'found'.$encoding_detected;
        else
            echo 'not found';
```

But detects UTF8 also returning GB18030...

So at the end I will go for something as lame as:

```
        $res = slugifier\slugify($title);

        //in case empty return because the usage of CJK characters....
        return (strlen($res)==0 AND strlen($title)>0) ? $title:$res;
```

So if slugify returns empty but original had length then use original....

**Comment by keyvanakbary** [comment]
Hey, thanks a lot for the report! Sorry for the delay.

PHP multibyte support is somewhat complicated, it's pretty difficult to cover all cases and I would like to keep the library as simple as possible. I think using the Elvis operator on those cases does the job good enough

``` php
$slug = s\slugify($text) ?: 'n-a';
```

Or in your specific case

``` php
return s\slugify($title) ?: $title;
```

What do you think?

**Comment by neo22s** [comment]
winner:

```
return s\slugify($title) ?: $title;
```

thanks ;)

**Comment by keyvanakbary** [comment]
:)
